<?php
/**
 * @author Greenrivers Team
 * @copyright Copyright (c) 2021 Greenrivers
 * @package Greenrivers_MaintenanceMode
 */

use Greenrivers\MaintenanceMode\pub\errors\Processor;

/** @var Processor $this */
if ($this->overrideTemplate()) : ?>
    <?= /* @noEscape */ $this->getPageContent() ?>
<?php else : ?>
    <h1>Service Temporarily Unavailable</h1>
    <p>
        The server is temporarily unable to service your request due to maintenance downtime or capacity problems.
        Please try again later.
    </p>
<?php endif; ?>
