<?php
/**
 * @author Greenrivers Team
 * @copyright Copyright (c) 2021 Greenrivers
 * @package Greenrivers_MaintenanceMode
 */

use Greenrivers\MaintenanceMode\pub\errors\Processor;

/** @var Processor $this */
?>

<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title><?= $this->pageTitle ?></title>
    <base href="<?= $this->getViewFileUrl() ?>"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="robots" content="*"/>
    <style>
        <?= $this->getPageStyles() ?>
    </style>
</head>
<body>
<main class="page-main">
    <?php require_once $contentTemplate; ?>
</main>
</body>
</html>
