<?php

use GreenRivers\MaintenanceMode\Block\Adminhtml\System\Config\Time;

/** @var Time $block */
$component = $block->getComponent();

$htmlId = $block->getElement()->getHtmlId();

$elementHtml = $block->getTimeElementHtml();
$elementName = $block->getTimeElementName();

$elementValue = $component['value'];
?>

<div class="admin__field-control">
    <?= $elementHtml ?>
</div>
<script>
    require([
        'jquery',
        'domReady!'
    ], function ($) {
        $(function () {
            const formName = 'time';

            setInitValue();

            function setInitValue() {
                const value = '<?= $elementValue ?>';
                $('#row_<?= $htmlId ?> .admin__field-control input:first')
                    .prop('name', "<?= $component['name'] ?>")
                    .val(value);

                const values = value.split(',');
                $(`#row_<?= $htmlId ?> .admin__field-control select[data-ui-id="system-config-form-0-element-time-time-hour"]`).val(values[0]);
                $(`#row_<?= $htmlId ?> .admin__field-control select[data-ui-id="system-config-form-0-element-time-time-minute"]`).val(values[1]);
                $(`#row_<?= $htmlId ?> .admin__field-control select[data-ui-id="system-config-form-0-element-time-time-second"]`).val(values[2]);
            }

            $(`#row_<?= $htmlId ?> .admin__field-control select[name="${formName}"]`).on('change', function () {
                let time = '';

                $(`#row_<?= $htmlId ?> .admin__field-control select[name="${formName}"]`).each(function (i, el) {
                    const id = $(el).data('ui-id');
                    const value = $(el).val();

                    if (id === 'system-config-form-0-element-time-<?= $elementName ?>-hour') {
                        time = value;
                    } else {
                        time += `,${value}`;
                    }
                });

                $('input[name="<?= $component['name'] ?>"]').val(time);
            });
        });
    });
</script>
